presets:
    - name: Default
      closeRobloxHours: 0
      planterSettingsMigrated: false
      discord:
        enabled: false
      join:
        fallbackToPublicServer: true
        preferredHiveSlot: 1
        hiveClaimMethod: detect
      window:
        windowConfigId: ""
        windowSize: full
      player:
        moveSpeed: 24
      patterns:
        defaults:
            - config:
                position: bottom-left
                length: 6
                width: 6
                distance: 3
                alignment: 25
                repetitions: 4
                yaw: 6
                zoom: 3
                gatherPattern: CornerXSnake
              field: dandelion
            - config:
                position: center
                length: 8
                width: 2
                distance: 3
                driftComp: true
                gatherPattern: e_lol
              field: clover
            - config:
                position: center
                length: 1
                width: 1
                yaw: 6
                walkReturn: true
                gatherPattern: Bamboo
              field: bamboo
            - config:
                position: bottom-right
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 4
                gatherPattern: CornerXSnake
              field: strawberry
            - config:
                position: bottom-left
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 4
                invertLR: true
                gatherPattern: CornerXSnake
              field: rose
            - config:
                position: center
                length: 8
                width: 2
                yaw: 2
                zoom: 4
                invertLR: true
                driftComp: true
                gatherPattern: e_lol
              field: mountain
            - config:
                position: bottom-right
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 4
                gatherPattern: CornerXSnake
              field: mushroom
            - config:
                position: center
                length: 8
                width: 2
                distance: 4
                yaw: 2
                driftComp: true
                gatherPattern: e_lol
              field: sunflower
            - config:
                position: bottom-right
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 4
                gatherPattern: CornerXSnake
              field: spider
            - config:
                position: bottom-right
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 4
                gatherPattern: CornerXSnake
              field: pineapple
            - config:
                position: center
                length: 8
                width: 2
                distance: 3
                driftComp: true
                gatherPattern: e_lol
              field: cactus
            - config:
                position: bottom-right
                length: 1
                width: 1
                distance: 5
                pitch: 3
                seconds: 600
                gatherPattern: Kettle
              field: pinetree
            - config:
                position: top-right
                length: 6
                width: 6
                alignment: 15
                repetitions: 4
                invertLR: true
                gatherPattern: CornerXSnake
              field: coconut
            - config:
                position: center
                length: 1
                width: 1
                yaw: 6
                walkReturn: true
                gatherPattern: BlueFlower
              field: blueflower
            - config:
                position: center
                length: 8
                width: 2
                yaw: 6
                driftComp: true
                gatherPattern: e_lol
              field: stump
            - config:
                position: bottom-left
                length: 6
                width: 6
                distance: 3
                alignment: 15
                repetitions: 4
                yaw: 6
                gatherPattern: CornerXSnake
              field: pumpkin
            - config:
                position: bottom-right
                length: 6
                width: 6
                alignment: 15
                repetitions: 4
                yaw: 4
                gatherPattern: CornerXSnake
              field: pepper
        active: []
        alignmentLevel: low
      dispensers:
        blueberry: false
        strawberry: false
        coconut: false
        treat: false
        honey: false
        wealthClock: false
        antPass: false
        roboPass: false
        royalJelly: false
        glue: false
        honeystorm:
            enabled: false
            gatherTokens: false
        stickerPrinter:
            enabled: false
            eggType: basic
        beesmas:
            stockings: false
            honeyWreath: false
            beesmasFeast: false
            gingerbreadHouse: false
            snowMachine: false
            candles: false
            samovar: false
            lidArt: false
      routing:
        tasks: []
        disableCannon: false
        disableGlider: false
        safePaths: false
        alignmentStuds: 0
        maxTaskRetries: 5
      convert:
        convertBalloon: true
        minMinutes: 0
        maxMinutes: 30
        minBackpackPercent: 0
        maxBackpackPercent: 80
        minBlessing: 0
        finishAfterRefresh: true
      gather:
        ai:
            tokens:
                - type: Baby Love
                  disabled: false
                  priority: 94
                - type: Long Buff
                  disabled: false
                  priority: 90
                - type: Token Link
                  disabled: false
                  priority: 10000
                - type: Bomb
                  disabled: false
                  priority: 85
                - type: Festive Gift
                  disabled: false
                  priority: 85
                - type: Focus
                  disabled: false
                  priority: 97
                - type: Frogs
                  disabled: false
                  priority: 91
                - type: Inspire
                  disabled: false
                  priority: 95.5
                - type: Loot
                  disabled: false
                  priority: 65
                - type: Tornado
                  disabled: false
                  priority: 90
                - type: Bear Morph
                  disabled: false
                  priority: 150
                - type: Inflate Balloons
                  disabled: false
                  priority: 91
                - type: Blue Pulse
                  disabled: false
                  priority: 1
                - type: Balloon
                  disabled: false
                  priority: 80
                - type: Gumdrop Barrage
                  disabled: false
                  priority: 1
                - type: Sprinkler
                  disabled: false
                  priority: 1
                - type: Boost
                  disabled: false
                  priority: 88
                - type: Fuzz Bombs
                  disabled: false
                  priority: 75
                - type: Gumdrop
                  disabled: false
                  priority: 50
                - type: Haste
                  disabled: false
                  priority: 95
                - type: Melody
                  disabled: false
                  priority: 96
                - type: Party Balloons
                  disabled: false
                  priority: 92
                - type: Tabby Love
                  disabled: false
                  priority: 92
                - type: Tabby Scratch
                  disabled: false
                  priority: 1
                - type: Blue Sync
                  disabled: false
                  priority: 93
                - type: Honey Token
                  disabled: false
                  priority: 0
                - type: Mark
                  disabled: false
                  priority: 76
            useFullModel: false
            maxFPS: 10
            lootMode: false
            ecoMode: false
        disableGathering: false
        useDipper: true
        inactiveHoneyTimeout: 10
        fullBackpackTimeout: 5
        fastPineReturnPath: false
        sprinklerType: supreme
        sprinklerSpacing: 12
      quest:
        polarBear:
            enabled: false
            priority: 0
            interrupt: false
            useGumdrops: false
        blackBear:
            enabled: false
            priority: 0
            interrupt: false
            useGumdrops: false
        brownBear:
            enabled: false
            priority: 0
            interrupt: false
            useGumdrops: false
        rileyBee:
            enabled: false
            priority: 0
            interrupt: false
            useGumdrops: false
        buckoBee:
            enabled: false
            priority: 0
            interrupt: false
            useGumdrops: false
      vicHop:
        enabled: false
        role: main
        serverHop: true
        claimHive: false
        hopTimeout: 30
        skipSpider: false
        skipPepper: false
        joinNewBattle: true
        joinInProgressBattle: true
        vicMinHealthPercent: 0.2
        detectionThreshold: 0.9
        joinEmptyServers: false
        rejoinAfterHours: 2
      mondoHop:
        enabled: false
        role: main
        lootSeconds: 30
      rbcGather:
        enabled: false
        role: main
        redPollenField: mushroom
        bluePollenField: blueflower
        whitePollenField: dandelion
        anyPollenField: mushroom
        fieldNavigationMode: hard-easy
        switchThreshold: 80
        altRejoinOnDeath: false
        altResetDisabled: false
        detectQuestAfterRound: 5
        maxAltsOnField: 2
      buff:
        consumables: []
        mondo:
            enabled: false
            buffTime: 60
            kill: false
            useAI: false
            interrupt: false
        stickerStack:
            enabled: false
            useTickets: true
            useStickers: false
            interrupt: false
        tadSync:
            enabled: false
            role: main
            usePineAltPattern: true
            useBambooAltPattern: true
            useBlueFlowerAltPattern: true
            returnField: pinetree
            resetToField: false
            glitterExtension: false
            glitterFields: []
        hqBooster:
            redBooster: false
            blueBooster: false
            mountainBooster: false
            gatherBoostedField: false
            restrictedFields: []
      alt: {}
      macro:
        keyDelay: 50
        loadTimeout: 30
        beesmasForceEnabled: false
        includeTextInHourlyEmbed: true
        discordRichPresenceEnabled: false
      kill:
        monsterRespawnPercent: 0
        bugRun:
            ladybug:
                loot: true
                minTime: 0
                enabledFields: []
            rhinoBeetle:
                loot: true
                minTime: 0
                enabledFields: []
            spider:
                loot: true
                minTime: 0
                enabledFields: []
            mantis:
                loot: true
                minTime: 0
                enabledFields: []
            scorpion:
                loot: true
                minTime: 0
                enabledFields: []
            werewolf:
                loot: true
                minTime: 0
                enabledFields: []
      planter:
        disabled: false
        gatherLoot: true
        searchMissingPlanters: false
        pathfindWhenPlanting: false
        resetWhenHarvesting: false
        useTimeAsCursor: false
        autoPlanters:
            enabled: false
            harvestAutomatically: false
            harvestAfterHours: 2
            harvestMinHours: 2
            harvestFullyGrown: false
            buildNectars: 3
            maintainNectars: 0
            degradationMultiplier: 1.2
            maxPlanters: 3
            fields: []
            planters: []
            nectars: []
windows:
    - id: Default
      alignment: top-left
      fullWidth: true
      screen: 0
tools:
    jellyTool:
        enabled: false
        beeTypes: []
        requireMutation: false
        mutationType: Movespeed
        mutationValue: 0
        usePercent: false
        stopGifted: false
        stopMythic: false
    serverHop:
        enabled: false
        joinEmpty: false
        stopAtNight: true
        maxHops: 0
networking:
    autoStart: false
    autoConnect: false
    bindAddress: ""
    enableTor: false
graphics:
    preferredCaptureMode: legacy
    detectionFrameRate: 10
    disableReporting: false
    disableMacLowDPIPatching: false
discord:
    enabled: true
    token: ""
    channel: ""
    botPrefix: '!'
    useSlashCommands: true
hotkeys:
    hotkeys:
        - name: Start
          sequence: F1
        - name: Pause
          sequence: F2
        - name: Stop
          sequence: F3
    start: F1
    pause: F2
    stop: F3
alwaysOnTop: false
logLevel: 0
logFilterTypes: ERROR,INFO
logShowTimestamps: false
devMode: false
theme: dark
version: 0.9b-hotfix2
cameraSensitivity: 0
discordRichPresencePromptShowed: true
